name: dllimport_gen
description: A code generation tool that aims to quickly generate dart code from the windows api documentation emulating the DllImport notation in C#.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  source_gen: ^0.9.5
  analyzer: ^0.39.8
  build: ^1.3.0

dev_dependencies:
  effective_dart: ^1.2.0
